### ISSUE TITLE
The example given in README.md does not work as shown

### ISSUE THREAD

**Issue by krishnakumarg1984** [Konfekt/vim-sentence-chopper#5]
When invoking `gwip` on the example text `Hello! How are you? Fine. And you?` produces:

>Hello!
How are you?
Fine. And you?

Notice how the last line has two sentences, which differs from the example output in the README.md.

**Comment by Konfekt** [comment]
Nice catch! This happens since addressing #2 trimming trailing blanks, since now for single word sentences the initial blanks of the single word sentence are already matched as the trailing blanks of the sentence preceding it.
I am not sure how to work around it easily;
I gave priority to keeping removing the trailing blanks to the detriment of splitting up single word sentences.
So rather a Won't Fix for the moment, though it made me rework the substitution regex.

**Comment by krishnakumarg1984** [comment]
@Konfekt So, this is an expected "won't fix" case? `gww` on the original text still does not produce the desired one sentence per line output.

**Comment by Konfekt** [comment]
It was not expected, you caught me there.
If you deem single word sentences relevant, then one option would be to remove the removal of blanks in the regex and instead add an extra command for trimming the white spaces after sentence endings

**Comment by krishnakumarg1984** [comment]
Will latexindent.pl be able to accommodate the per-line formatting of such single-word sentences?

**Comment by Konfekt** [comment]
@cmhuges could you tell whether latexindent.pl, maybe in the future,  takes account of single-word sentences?
